import type {
  CommitPolicy,
  RemediationProgramDefinition,
  RemediationUnit,
  RunnerPolicy,
} from "../types.ts";

const PROGRAM_ID = "finance-pages";
const ARTIFACT_ROOT = "plans/remidation/artifacts/finance-pages";

const ALL_AUDIT_SKILLS = [
  "next-best-practices",
  "vercel-react-best-practices",
  "vercel-composition-patterns",
] as const;

const FINANCE_ROUTE_CONFIGS = [
  "app/(marketing)/(financing)/rollback-financing/config.ts",
  "app/(marketing)/(financing)/wrecker-financing/config.ts",
  "app/(marketing)/(financing)/rotator-financing/config.ts",
  "app/(marketing)/(financing)/used-tow-truck-financing/config.ts",
] as const;

const FINANCE_ROUTE_PAGES = [
  "app/(marketing)/(financing)/rollback-financing/page.tsx",
  "app/(marketing)/(financing)/wrecker-financing/page.tsx",
  "app/(marketing)/(financing)/rotator-financing/page.tsx",
  "app/(marketing)/(financing)/used-tow-truck-financing/page.tsx",
] as const;

const DEFAULT_COMMIT_POLICY: CommitPolicy = {
  mode: "stage-and-approve",
  provenanceRequired: true,
};

const DEFAULT_RUNNER_POLICY_BY_WAVE: Record<1 | 2 | 3 | 4 | 5, RunnerPolicy> = {
  1: {
    mode: "supervised-auto-run",
    adapter: "codex",
    rationale: "Low-risk nonvisual finance fixes.",
  },
  2: {
    mode: "supervised-auto-run",
    adapter: "codex",
    rationale: "Accessibility and interaction fixes still stop after each unit.",
  },
  3: {
    mode: "interactive-review",
    adapter: "codex",
    rationale: "Architecture units need stronger human review before commit.",
  },
  4: {
    mode: "interactive-review",
    adapter: "codex",
    rationale: "Higher visual-regression risk architecture refactors.",
  },
  5: {
    mode: "supervised-auto-run",
    adapter: "codex",
    rationale: "Low-risk cleanup after earlier waves merge.",
  },
};

function reportPath(unitId: string) {
  return `${ARTIFACT_ROOT}/${unitId}/fix-report.md`;
}

function branchFor(wave: number, unitId: string) {
  return `remediation/${PROGRAM_ID}/wave-${wave}/${unitId.toLowerCase()}`;
}

function defineUnit(unit: Omit<RemediationUnit, "programId" | "branch" | "fixReportPath">): RemediationUnit {
  return {
    ...unit,
    programId: PROGRAM_ID,
    branch: branchFor(unit.wave, unit.id),
    fixReportPath: reportPath(unit.id),
  };
}

export const financePagesProgram: RemediationProgramDefinition = {
  program: {
    programId: PROGRAM_ID,
    displayName: "Finance Pages Remediation",
    baseBranch: "main",
    registryPath: "scripts/remediation/programs/finance-pages.ts",
    trackerPath: "plans/remidation/finance-pages-tracker.json",
    statusPath: "plans/financing-pages/financing-status.md",
    artifactRoot: ARTIFACT_ROOT,
    baselineConfig: {
      defaultViewports: ["desktop", "mobile"],
      enforceLintBaseline: true,
      enforceBuildBaseline: true,
    },
    defaultRunnerPolicyByWave: DEFAULT_RUNNER_POLICY_BY_WAVE,
    defaultCommitPolicy: DEFAULT_COMMIT_POLICY,
    defaultAttemptBudget: 3,
    requiredControlFiles: [
      "plans/remidation/plan.md",
      "plans/remidation/reusable-remediation-harness-roadmap.md",
      "plans/financing-pages/financing-findings-ledger.md",
      "plans/financing-pages/financing-status.md",
    ],
  },
  units: [
    defineUnit({
      id: "FIN-metadata-001",
      wave: 1,
      title: "Move route metadata ownership back into financing page files",
      type: "bugfix-nonvisual",
      sourceRef: {
        kind: "ledger",
        path: "plans/financing-pages/financing-findings-ledger.md",
        findingIds: ["FIN-metadata-001"],
        evidencePaths: ["plans/financing-pages/financing-step-02b-shell-config.md"],
      },
      allowedFiles: [
        ...FINANCE_ROUTE_PAGES,
        ...FINANCE_ROUTE_CONFIGS,
        "app/(marketing)/(financing)/_components/page-config-types.ts",
      ],
      dependsOn: [],
      requiredSkills: [...ALL_AUDIT_SKILLS],
      claudeMdHints: ["app/(marketing)/CLAUDE.md"],
      requiresTests: false,
      requiresBrowserValidation: false,
      requiresVisualRegression: false,
      browserChecks: [],
      ownerSurface: "financing-route-metadata",
      tags: ["metadata", "route-ownership", "nonvisual"],
      baselineRoutes: [],
      visualChangeScope: "none",
      rollbackHints: [
        "Restore metadata fields to the route config files and revert page-level exports if ownership needs to roll back.",
      ],
    }),
    defineUnit({
      id: "FIN-architecture-002",
      wave: 3,
      title: "Remove dormant financing sections from the base shell contract",
      type: "architecture",
      sourceRef: {
        kind: "ledger",
        path: "plans/financing-pages/financing-findings-ledger.md",
        findingIds: ["FIN-architecture-002"],
        evidencePaths: [
          "plans/financing-pages/financing-step-02b-shell-config.md",
          "plans/financing-pages/financing-step-04c-dormant-mid-sections.md",
        ],
      },
      allowedFiles: [
        "app/(marketing)/(financing)/_components/EquipmentFinancingPageShell.tsx",
        "app/(marketing)/(financing)/_components/page-config-types.ts",
        "app/(marketing)/(financing)/_components/shared-config.ts",
        ...FINANCE_ROUTE_CONFIGS,
      ],
      dependsOn: [],
      requiredSkills: [...ALL_AUDIT_SKILLS],
      claudeMdHints: [
        "app/(marketing)/CLAUDE.md",
        "components/sections/page/program-cards/CLAUDE.md",
      ],
      requiresTests: false,
      requiresBrowserValidation: false,
      requiresVisualRegression: false,
      browserChecks: [],
      ownerSurface: "financing-shell-contract",
      tags: ["architecture", "composition", "dormant-sections"],
      baselineRoutes: [],
      visualChangeScope: "none",
      rollbackHints: [
        "Reintroduce dormant section slots only via an explicit extended config variant, not the base shell contract.",
      ],
    }),
    defineUnit({
      id: "FIN-faq-unification",
      wave: 3,
      title: "Unify FAQ answer data and single-pass FAQ payload construction",
      type: "architecture",
      sourceRef: {
        kind: "ledger",
        path: "plans/financing-pages/financing-findings-ledger.md",
        findingIds: ["FIN-config-003", "FIN-schema-016"],
        evidencePaths: [
          "plans/financing-pages/financing-step-02b-shell-config.md",
          "plans/financing-pages/financing-step-06a-faq.md",
        ],
        notes: "Composite remediation unit replacing prose-only coupling between FIN-config-003 and FIN-schema-016.",
      },
      allowedFiles: [
        "app/(marketing)/(financing)/_components/shared-config.ts",
        "app/(marketing)/(financing)/_components/page-config-types.ts",
        ...FINANCE_ROUTE_CONFIGS,
        "components/sections/page/faq/config.ts",
        "components/sections/page/faq/FAQ.tsx",
        "components/sections/page/faq/FaqSection.tsx",
        "components/sections/page/faq/index.ts",
        "components/sections/page/faq/CLAUDE.md",
      ],
      dependsOn: [],
      requiredSkills: [...ALL_AUDIT_SKILLS],
      claudeMdHints: ["components/sections/page/faq/CLAUDE.md"],
      requiresTests: false,
      requiresBrowserValidation: true,
      requiresVisualRegression: false,
      browserChecks: [
        {
          route: "/rollback-financing#faq",
          viewport: "both",
          assertions: [
            "FAQ renders in-flow and one item remains expanded by the single-open accordion logic.",
            "Schema and visible answer copy are produced from the same canonical answer source.",
          ],
        },
      ],
      ownerSurface: "faq-contract-and-financing-configs",
      tags: ["faq", "schema", "config", "composite-unit"],
      baselineRoutes: [],
      visualChangeScope: "none",
      rollbackHints: [
        "If the unified contract needs to roll back, revert both the shared FAQ config model and each route's FAQ builder changes together.",
      ],
    }),
    defineUnit({
      id: "FIN-bundle-004",
      wave: 1,
      title: "Scope the drawer provider to the financing segment",
      type: "bugfix-nonvisual",
      sourceRef: {
        kind: "ledger",
        path: "plans/financing-pages/financing-findings-ledger.md",
        findingIds: ["FIN-bundle-004"],
        evidencePaths: ["plans/financing-pages/financing-step-02c-schema-drawer.md"],
      },
      allowedFiles: [
        "app/layout.tsx",
        "app/(marketing)/(financing)/layout.tsx",
        "components/ui/pre-approval-drawer/DrawerContext.tsx",
        "components/ui/pre-approval-drawer/index.ts",
        "components/ui/pre-approval-drawer/CLAUDE.md",
      ],
      dependsOn: [],
      requiredSkills: ["next-best-practices", "vercel-react-best-practices"],
      claudeMdHints: ["components/ui/pre-approval-drawer/CLAUDE.md"],
      requiresTests: false,
      requiresBrowserValidation: true,
      requiresVisualRegression: false,
      browserChecks: [
        {
          route: "/rollback-financing",
          viewport: "desktop",
          assertions: [
            "Drawer still opens from a financing route after the provider moves out of RootLayout.",
          ],
        },
      ],
      ownerSurface: "drawer-layout-boundary",
      tags: ["bundle", "drawer", "segment-layout"],
      baselineRoutes: [],
      visualChangeScope: "none",
      rollbackHints: [
        "Restore RootLayout ownership if financing-segment-only mounting breaks same-page drawer triggers.",
      ],
    }),
    defineUnit({
      id: "FIN-cta-005",
      wave: 1,
      title: "Keep same-page drawer CTA behavior on used truck financing",
      type: "bugfix-nonvisual",
      sourceRef: {
        kind: "ledger",
        path: "plans/financing-pages/financing-findings-ledger.md",
        findingIds: ["FIN-cta-005"],
        evidencePaths: ["plans/financing-pages/financing-step-02c-schema-drawer.md"],
      },
      allowedFiles: [
        "components/ui/pre-approval-drawer/config.ts",
        "components/sections/nav/sticky-nav-rm/NavClient.tsx",
      ],
      dependsOn: [],
      requiredSkills: ["next-best-practices", "vercel-react-best-practices"],
      claudeMdHints: ["components/ui/pre-approval-drawer/CLAUDE.md"],
      requiresTests: false,
      requiresBrowserValidation: true,
      requiresVisualRegression: false,
      browserChecks: [
        {
          route: "/used-tow-truck-financing",
          viewport: "both",
          assertions: [
            "Sticky-nav primary CTA resolves to the same-page drawer hash instead of the rollback route.",
          ],
        },
      ],
      ownerSurface: "drawer-cta-routing",
      tags: ["cta", "drawer", "navigation"],
      baselineRoutes: [],
      visualChangeScope: "none",
      rollbackHints: [
        "Restore the previous fallback route only if the used-truck page can no longer mount the same drawer flow.",
      ],
    }),
    defineUnit({
      id: "FIN-architecture-006",
      wave: 3,
      title: "Give the framed hero family its own local config contract",
      type: "architecture",
      sourceRef: {
        kind: "ledger",
        path: "plans/financing-pages/financing-findings-ledger.md",
        findingIds: ["FIN-architecture-006"],
        evidencePaths: ["plans/financing-pages/financing-step-03a-hero-wrappers.md"],
      },
      allowedFiles: [
        "components/sections/heroes/hero-convert-framed/HeroConvertFramed.tsx",
        "components/sections/heroes/hero-convert-framed/HeroConvertFramedOutline.tsx",
        "components/sections/heroes/hero-convert-framed/HeroConvertFramedPrimaryOnly.tsx",
        "components/sections/heroes/hero-convert-framed/HeroConvertFramedTileRight.tsx",
        "components/sections/heroes/hero-convert-framed/index.ts",
        "components/sections/heroes/hero-convert-framed/framed-config.ts",
        "components/sections/heroes/hero-convert-framed/CLAUDE.md",
      ],
      dependsOn: [],
      requiredSkills: [...ALL_AUDIT_SKILLS],
      claudeMdHints: ["components/sections/heroes/hero-convert-framed/CLAUDE.md"],
      requiresTests: false,
      requiresBrowserValidation: false,
      requiresVisualRegression: false,
      browserChecks: [],
      ownerSurface: "hero-convert-framed-contract",
      tags: ["architecture", "hero", "config-ownership"],
      baselineRoutes: [],
      visualChangeScope: "none",
      rollbackHints: [
        "If needed, revert to the sibling config type only as a temporary rollback and preserve the new local contract file for a later retry.",
      ],
    }),
    defineUnit({
      id: "FIN-patterns-007",
      wave: 4,
      title: "Extract shared framed hero shell building blocks",
      type: "architecture",
      sourceRef: {
        kind: "ledger",
        path: "plans/financing-pages/financing-findings-ledger.md",
        findingIds: ["FIN-patterns-007"],
        evidencePaths: ["plans/financing-pages/financing-step-03a-hero-wrappers.md"],
      },
      allowedFiles: [
        "components/sections/heroes/hero-convert-framed/HeroConvertFramed.tsx",
        "components/sections/heroes/hero-convert-framed/HeroConvertFramedOutline.tsx",
        "components/sections/heroes/hero-convert-framed/HeroConvertFramedPrimaryOnly.tsx",
        "components/sections/heroes/hero-convert-framed/HeroConvertFramedTileRight.tsx",
        "components/sections/heroes/hero-convert-framed/HeroGallery.tsx",
        "components/sections/heroes/hero-convert-framed/shared-shell.tsx",
        "components/sections/heroes/hero-convert-framed/index.ts",
        "components/sections/heroes/hero-convert-framed/CLAUDE.md",
      ],
      dependsOn: ["FIN-architecture-006"],
      requiredSkills: [...ALL_AUDIT_SKILLS],
      claudeMdHints: ["components/sections/heroes/hero-convert-framed/CLAUDE.md"],
      requiresTests: false,
      requiresBrowserValidation: true,
      requiresVisualRegression: true,
      browserChecks: [
        {
          route: "/wrecker-financing",
          viewport: "both",
          assertions: [
            "Framed hero variant still renders with the same CTA enablement and media layout behavior after shell extraction.",
          ],
        },
      ],
      ownerSurface: "hero-convert-framed-shared-shell",
      tags: ["architecture", "hero", "shared-shell", "dependency-fin-architecture-006"],
      baselineRoutes: [
        "/rollback-financing",
        "/wrecker-financing",
        "/used-tow-truck-financing",
      ],
      visualChangeScope: "none",
      rollbackHints: [
        "Revert shared-shell extraction as one unit if any hero variant drifts visually or behaviorally.",
      ],
    }),
    defineUnit({
      id: "FIN-a11y-008",
      wave: 2,
      title: "Upgrade the framed selector to radiogroup semantics",
      type: "bugfix-nonvisual",
      sourceRef: {
        kind: "ledger",
        path: "plans/financing-pages/financing-findings-ledger.md",
        findingIds: ["FIN-a11y-008"],
        evidencePaths: ["plans/financing-pages/financing-step-03b-hero-interactions.md"],
      },
      allowedFiles: [
        "components/sections/heroes/hero-convert-framed/FramedTileSelector.tsx",
        "components/sections/heroes/hero-convert-framed/FramedSelectionTile.tsx",
        "components/sections/heroes/hero-convert-framed/CLAUDE.md",
      ],
      dependsOn: [],
      requiredSkills: ["next-best-practices", "vercel-react-best-practices"],
      claudeMdHints: ["components/sections/heroes/hero-convert-framed/CLAUDE.md"],
      requiresTests: false,
      requiresBrowserValidation: true,
      requiresVisualRegression: false,
      browserChecks: [
        {
          route: "/wrecker-financing",
          viewport: "desktop",
          assertions: [
            "Arrow key navigation moves selection across hero tiles with radiogroup semantics.",
          ],
        },
      ],
      ownerSurface: "framed-tile-selector",
      tags: ["a11y", "keyboard", "hero-selector"],
      baselineRoutes: [],
      visualChangeScope: "none",
      rollbackHints: [
        "Preserve the existing visual tile treatment even if the ARIA model needs to revert.",
      ],
    }),
    defineUnit({
      id: "FIN-image-009",
      wave: 1,
      title: "Prioritize the hero gallery's initial desktop image",
      type: "bugfix-nonvisual",
      sourceRef: {
        kind: "ledger",
        path: "plans/financing-pages/financing-findings-ledger.md",
        findingIds: ["FIN-image-009"],
        evidencePaths: ["plans/financing-pages/financing-step-03b-hero-interactions.md"],
      },
      allowedFiles: [
        "components/sections/heroes/hero-convert-framed/HeroGallery.tsx",
        "components/sections/heroes/hero-convert-framed/HeroConvertFramed.tsx",
        "components/sections/heroes/hero-convert-framed/HeroConvertFramedOutline.tsx",
        "components/sections/heroes/hero-convert-framed/HeroConvertFramedPrimaryOnly.tsx",
        "app/(marketing)/(financing)/wrecker-financing/config.ts",
      ],
      dependsOn: [],
      requiredSkills: ["next-best-practices", "vercel-react-best-practices"],
      claudeMdHints: ["components/sections/heroes/hero-convert-framed/CLAUDE.md"],
      requiresTests: false,
      requiresBrowserValidation: true,
      requiresVisualRegression: false,
      browserChecks: [
        {
          route: "/wrecker-financing",
          viewport: "desktop",
          assertions: [
            "The active hero gallery image is no longer lazy-loaded on first render.",
          ],
        },
      ],
      ownerSurface: "hero-gallery-loading",
      tags: ["image", "lcp", "hero-gallery"],
      baselineRoutes: [],
      visualChangeScope: "none",
      rollbackHints: [
        "Revert to lazy loading only if priority introduces measurable regressions elsewhere in the hero gallery.",
      ],
    }),
    defineUnit({
      id: "FIN-a11y-010",
      wave: 1,
      title: "Restore list semantics for lead-gen hero trust badges",
      type: "bugfix-nonvisual",
      sourceRef: {
        kind: "ledger",
        path: "plans/financing-pages/financing-findings-ledger.md",
        findingIds: ["FIN-a11y-010"],
        evidencePaths: ["plans/financing-pages/financing-step-03c-hero-lead-gen.md"],
      },
      allowedFiles: [
        "components/sections/heroes/hero-lead-gen/HeroLeadGen.tsx",
        "components/sections/heroes/hero-lead-gen/TrustBadge.tsx",
        "components/sections/heroes/hero-lead-gen/CLAUDE.md",
      ],
      dependsOn: [],
      requiredSkills: ["next-best-practices", "vercel-react-best-practices"],
      claudeMdHints: ["components/sections/heroes/hero-lead-gen/CLAUDE.md"],
      requiresTests: false,
      requiresBrowserValidation: false,
      requiresVisualRegression: false,
      browserChecks: [],
      ownerSurface: "hero-lead-gen-trust-badges",
      tags: ["a11y", "semantics", "hero-lead-gen"],
      baselineRoutes: [],
      visualChangeScope: "none",
      rollbackHints: [
        "Keep decorative icon treatment separate from any list-semantics rollback.",
      ],
    }),
    defineUnit({
      id: "FIN-hydration-011",
      wave: 1,
      title: "Remove render-time date drift from the financing countdown chip",
      type: "bugfix-nonvisual",
      sourceRef: {
        kind: "ledger",
        path: "plans/financing-pages/financing-findings-ledger.md",
        findingIds: ["FIN-hydration-011"],
        evidencePaths: ["plans/financing-pages/financing-step-04a-strip-offers.md"],
      },
      allowedFiles: [
        "components/sections/page/financing-offers-split/CountdownChip.tsx",
        "components/sections/page/financing-offers-split/FinancingOffersSplit.tsx",
        "components/sections/page/financing-offers-split/config.ts",
        "components/sections/page/financing-offers-split/CLAUDE.md",
        "app/(marketing)/(financing)/rollback-financing/config.ts",
      ],
      dependsOn: [],
      requiredSkills: ["next-best-practices", "vercel-react-best-practices"],
      claudeMdHints: ["components/sections/page/financing-offers-split/CLAUDE.md"],
      requiresTests: false,
      requiresBrowserValidation: true,
      requiresVisualRegression: false,
      browserChecks: [
        {
          route: "/rollback-financing",
          viewport: "both",
          assertions: [
            "Countdown text remains stable across hydration and reflects one canonical date source.",
          ],
        },
      ],
      ownerSurface: "financing-offers-countdown",
      tags: ["hydration", "date-handling", "offers"],
      baselineRoutes: [],
      visualChangeScope: "none",
      rollbackHints: [
        "If reverting, keep the fallback mounted-state guard paired with the date-source rollback.",
      ],
    }),
    defineUnit({
      id: "FIN-a11y-012",
      wave: 2,
      title: "Expose an accessible brand list while keeping one duplicate track hidden",
      type: "bugfix-nonvisual",
      sourceRef: {
        kind: "ledger",
        path: "plans/financing-pages/financing-findings-ledger.md",
        findingIds: ["FIN-a11y-012"],
        evidencePaths: ["plans/financing-pages/financing-step-04b-brand-marquee.md"],
      },
      allowedFiles: [
        "components/sections/page/brand-marquee/BrandMarquee.tsx",
        "components/sections/page/brand-marquee/config.ts",
        "components/sections/page/brand-marquee/brand-marquee.css",
        "components/sections/page/brand-marquee/CLAUDE.md",
      ],
      dependsOn: [],
      requiredSkills: ["next-best-practices", "vercel-react-best-practices"],
      claudeMdHints: ["components/sections/page/brand-marquee/CLAUDE.md"],
      requiresTests: false,
      requiresBrowserValidation: true,
      requiresVisualRegression: false,
      browserChecks: [
        {
          route: "/rollback-financing",
          viewport: "desktop",
          assertions: [
            "One accessible manufacturer list is exposed while the duplicate animation track stays hidden from assistive tech.",
          ],
        },
      ],
      ownerSurface: "brand-marquee-accessibility",
      tags: ["a11y", "brand-marquee", "semantic-list"],
      baselineRoutes: [],
      visualChangeScope: "none",
      rollbackHints: [
        "If animation treatment has to roll back, preserve the accessible text alternative path.",
      ],
    }),
    defineUnit({
      id: "FIN-bundle-013",
      wave: 4,
      title: "Collapse purchase-and-terms to one responsive child composition path",
      type: "architecture",
      sourceRef: {
        kind: "ledger",
        path: "plans/financing-pages/financing-findings-ledger.md",
        findingIds: ["FIN-bundle-013"],
        evidencePaths: ["plans/financing-pages/financing-step-05a-purchase-wrapper.md"],
      },
      allowedFiles: [
        "components/sections/page/purchase-and-terms/PurchaseAndTermsSection.tsx",
        "components/sections/page/purchase-and-terms/config.ts",
        "components/sections/page/purchase-and-terms/CLAUDE.md",
        "components/sections/page/purchase-source-grid/PurchaseSourceGrid.tsx",
        "components/sections/page/term-length-slider/TermLengthSlider.tsx",
      ],
      dependsOn: [],
      requiredSkills: [...ALL_AUDIT_SKILLS],
      claudeMdHints: [
        "components/sections/page/purchase-and-terms/CLAUDE.md",
        "components/sections/page/purchase-source-grid/CLAUDE.md",
        "components/sections/page/term-length-slider/CLAUDE.md",
      ],
      requiresTests: false,
      requiresBrowserValidation: true,
      requiresVisualRegression: true,
      browserChecks: [
        {
          route: "/rollback-financing",
          viewport: "both",
          assertions: [
            "Only one purchase source grid and one term slider mount while the layout still stacks on mobile and splits on desktop.",
          ],
        },
      ],
      ownerSurface: "purchase-and-terms-wrapper",
      tags: ["bundle", "architecture", "responsive-composition"],
      baselineRoutes: ["/rollback-financing", "/wrecker-financing"],
      visualChangeScope: "none",
      rollbackHints: [
        "Revert the wrapper composition as a single unit if section layout or hydration behavior drifts.",
      ],
    }),
    defineUnit({
      id: "FIN-bundle-014",
      wave: 1,
      title: "Return the purchase source checklist to the server",
      type: "bugfix-nonvisual",
      sourceRef: {
        kind: "ledger",
        path: "plans/financing-pages/financing-findings-ledger.md",
        findingIds: ["FIN-bundle-014"],
        evidencePaths: ["plans/financing-pages/financing-step-05b-purchase-interactions.md"],
      },
      allowedFiles: [
        "components/sections/page/purchase-source-grid/PurchaseSourceGrid.tsx",
        "components/sections/page/purchase-source-grid/index.ts",
        "components/sections/page/purchase-source-grid/CLAUDE.md",
      ],
      dependsOn: [],
      requiredSkills: ["next-best-practices", "vercel-react-best-practices"],
      claudeMdHints: ["components/sections/page/purchase-source-grid/CLAUDE.md"],
      requiresTests: false,
      requiresBrowserValidation: false,
      requiresVisualRegression: false,
      browserChecks: [],
      ownerSurface: "purchase-source-grid-boundary",
      tags: ["bundle", "rsc", "server-component"],
      baselineRoutes: [],
      visualChangeScope: "none",
      rollbackHints: [
        "If client behavior is later required, reintroduce a narrow client island instead of restoring a whole-folder client boundary.",
      ],
    }),
    defineUnit({
      id: "FIN-image-015",
      wave: 1,
      title: "Right-size the content-image split sizes hint",
      type: "bugfix-nonvisual",
      sourceRef: {
        kind: "ledger",
        path: "plans/financing-pages/financing-findings-ledger.md",
        findingIds: ["FIN-image-015"],
        evidencePaths: ["plans/financing-pages/financing-step-05c-content-image-split.md"],
      },
      allowedFiles: [
        "components/sections/page/content-image-split/ContentImageSplit.tsx",
        "components/sections/page/content-image-split/CLAUDE.md",
      ],
      dependsOn: [],
      requiredSkills: ["next-best-practices", "vercel-react-best-practices"],
      claudeMdHints: ["components/sections/page/content-image-split/CLAUDE.md"],
      requiresTests: false,
      requiresBrowserValidation: false,
      requiresVisualRegression: false,
      browserChecks: [],
      ownerSurface: "content-image-split-image-slot",
      tags: ["image", "sizes", "rendering-performance"],
      baselineRoutes: [],
      visualChangeScope: "none",
      rollbackHints: [
        "Restore the previous sizes hint only if the capped slot calculation proves incorrect on audited breakpoints.",
      ],
    }),
    defineUnit({
      id: "FIN-a11y-017",
      wave: 2,
      title: "Make financing disclosures readable on mobile and desktop",
      type: "bugfix-visual-safe",
      sourceRef: {
        kind: "ledger",
        path: "plans/financing-pages/financing-findings-ledger.md",
        findingIds: ["FIN-a11y-017"],
        evidencePaths: ["plans/financing-pages/financing-step-06b-footnotes-links.md"],
      },
      allowedFiles: [
        "components/sections/page/financing-footnotes/FinancingFootnotes.tsx",
        "components/sections/page/financing-footnotes/CLAUDE.md",
      ],
      dependsOn: [],
      requiredSkills: ["next-best-practices", "vercel-react-best-practices"],
      claudeMdHints: ["components/sections/page/financing-footnotes/CLAUDE.md"],
      requiresTests: false,
      requiresBrowserValidation: true,
      requiresVisualRegression: true,
      browserChecks: [
        {
          route: "/rollback-financing",
          viewport: "both",
          assertions: [
            "Disclosure copy is visibly darker, larger, and readable without changing the section's structure.",
          ],
        },
      ],
      ownerSurface: "financing-footnotes-readability",
      tags: ["a11y", "contrast", "footnotes"],
      baselineRoutes: ["/rollback-financing", "/wrecker-financing"],
      visualChangeScope: "strict-minimum",
      visualChangeNotes: "Only the minimum typography and color changes needed for disclosure readability are allowed.",
      rollbackHints: [
        "If appearance must roll back, preserve the darker neutral token and size increase together rather than partially reverting.",
      ],
    }),
    defineUnit({
      id: "FIN-a11y-018",
      wave: 2,
      title: "Turn the related links strip into labeled, touch-friendly navigation",
      type: "bugfix-visual-safe",
      sourceRef: {
        kind: "ledger",
        path: "plans/financing-pages/financing-findings-ledger.md",
        findingIds: ["FIN-a11y-018"],
        evidencePaths: ["plans/financing-pages/financing-step-06b-footnotes-links.md"],
      },
      allowedFiles: [
        "components/sections/page/related-links-strip/RelatedLinksStrip.tsx",
        "components/sections/page/related-links-strip/config.ts",
        "components/sections/page/related-links-strip/CLAUDE.md",
      ],
      dependsOn: [],
      requiredSkills: ["next-best-practices", "vercel-react-best-practices"],
      claudeMdHints: ["components/sections/page/related-links-strip/CLAUDE.md"],
      requiresTests: false,
      requiresBrowserValidation: true,
      requiresVisualRegression: true,
      browserChecks: [
        {
          route: "/rollback-financing",
          viewport: "mobile",
          assertions: [
            "Related links render as labeled navigation with touch-friendly targets.",
          ],
        },
      ],
      ownerSurface: "related-links-strip",
      tags: ["a11y", "navigation", "tap-targets"],
      baselineRoutes: ["/rollback-financing"],
      visualChangeScope: "strict-minimum",
      visualChangeNotes: "Only the semantics and minimum target-size styling needed for the links section are allowed.",
      rollbackHints: [
        "If the visual treatment must be reduced, keep the navigation label and list semantics in place.",
      ],
    }),
    defineUnit({
      id: "FIN-a11y-019",
      wave: 2,
      title: "Promote the fallback phone contact into a touch-sized secondary action",
      type: "bugfix-visual-safe",
      sourceRef: {
        kind: "ledger",
        path: "plans/financing-pages/financing-findings-ledger.md",
        findingIds: ["FIN-a11y-019"],
        evidencePaths: ["plans/financing-pages/financing-step-06c-closing-cta.md"],
      },
      allowedFiles: [
        "components/sections/page/equipment-closing-cta/EquipmentClosingCta.tsx",
        "components/sections/page/equipment-closing-cta/config.ts",
        "components/sections/page/equipment-closing-cta/CLAUDE.md",
      ],
      dependsOn: [],
      requiredSkills: ["next-best-practices", "vercel-react-best-practices"],
      claudeMdHints: ["components/sections/page/equipment-closing-cta/CLAUDE.md"],
      requiresTests: false,
      requiresBrowserValidation: true,
      requiresVisualRegression: true,
      browserChecks: [
        {
          route: "/rollback-financing",
          viewport: "mobile",
          assertions: [
            "Fallback phone contact renders as a touch-sized secondary action below the primary CTA.",
          ],
        },
      ],
      ownerSurface: "equipment-closing-cta-contact-block",
      tags: ["a11y", "closing-cta", "tap-target"],
      baselineRoutes: ["/rollback-financing"],
      visualChangeScope: "strict-minimum",
      visualChangeNotes: "Only the minimum styling change required to make the phone action touch-friendly is allowed.",
      rollbackHints: [
        "If needed, revert the visual wrapper while keeping any improved semantic labeling or hit-area sizing that remains valid.",
      ],
    }),
  ],
};

export const financePagesUnits = financePagesProgram.units;
